# === meta ===
pair: "BTCUSDT"
timeframe: "15m"                  # 정보용(의사결정 TF). 실계산은 1m + MTF 병합

# === I/O & debug ===
io:
  write_debug_json: true
  debug_limit_examples: 12

# === indicators (pandas_ta 우선, 실패 시 네이티브 폴백) ===
indicators:
  use_pandas_ta: true
  rsi_length: 14
  bb_length: 20
  bb_std: 2.0
  atr_length: 14
  ema_length: 21
  adx_length: 14
  macd:  { fast: 12, slow: 26, signal: 9 }
  stoch: { k: 14, d: 3, smooth: 3 }
  vol_ma_length: 50                # 볼륨 스파이크 기준선
  bb_squeeze_th: 0.028
  with_adx: true
  with_stoch: false
  with_cci: false
  with_ichimoku: false

# === features (core/features.py) ===
features:
  volume_window: 100               # 거래량 Z-score 윈도
  ema_slope_lookback: 5            # (참고) 실제 slope는 regime.* 값으로 계산

# === regime (EMA 기울기 + BB폭 + ADX) ===
regime:
  trend_adx_min: 26                # 약추세 컷
  range_bb_width_max: 0.0020
  ema_slope_lookback: 5
  ema_slope_min: 0.0007            # 레짐 판단 허들(엔트리 순간은 filters에서 별도 체크)

# === MTF driver (15m가 방향 결정, 1m는 타이밍) ===
mtf_driver:
  enable: true
  decision_tf: "15m"               # 드라이버 타임프레임
  confirm_on_close: true           # 닫힌 15m 캔들 기준
  entry_window_minutes: 20         # 15m 확정 후 N분 내 1m 진입 허용
  rsi_min: 55                      # 15m RSI 기반 방향 필터
  use_macd: true
  macd_deadband_mode: "pct_of_atr" # abs | pct_of_close | pct_of_atr
  macd_deadband: 0.0               # abs 모드일 때만 사용
  macd_deadband_pct: 0.08          # ATR의 8% 정도 → 과잠김 방지
  ema_bias: true                   # 15m close vs ema21 동의 요구
  require_higher_agree: []         # 초기엔 OFF. 튠 후 ["1h"] → ["1h","4h"] 단계적 적용 권장
  higher_rsi_min: 52.0
  higher_ema_slope_min: 0.0002

# === thresholding (적응식 임계값 + 세션 스케일 비교) ===
thresholding:
  mode: adaptive
  adaptive_percentile: 0.970       # 신호 희소화. 많으면 ↑, 마르면 ↓ (0.965~0.975 구간 튠)
  window_bars: 4320
  floor: 78                        # 스코어 하한(말라버림 방지)
  compare: session_scaled          # 세션 배수 곱한 뒤 임계 비교
  fixed_score_th: 80               # mode=fixed일 때 백업값

# === entries ===
entries:
  cooldown_bars: 120               # 재진입 쿨다운(1m 바 기준)

# === position / risk / trailing ===
position:
  add_on_max: 0
  add_on_trigger_R: 0.8
  add_on_size_pct: 33
  ladder: []
  be_at_R: 1.6                     # BE 승격 타이밍
  partials:
    - { trigger_R: 1.2, pct: 15 }
    - { trigger_R: 2.2, pct: 25 }

risk:
  rr_base:  [1, 3]
  rr_trend: [1, 3.2]               # 추세 러너 약간 확장
  rr_range: [1, 1.9]
  atr_sl_mult_trend: 1.7
  atr_sl_mult_range: 1.0
  max_hold_minutes: 360
  fees_bps_per_side: 2
  daily_loss_limit_R: 6

trailing:
  enable_rsi: true
  rsi_on_long: 62
  rsi_on_short: 38
  trail_start_R: 1.6
  wait_first_ladder: false
  atr_trail_mult_trend: 1.7
  atr_trail_mult_range: 1.2

# === session ===
session:
  block: []                        # 차단 세션 없음
  score_mult: { US: 1.10, EU: 1.00, ASIA: 0.95 }   # US 약간 우대
  risk_adj:   { US: 1.00, EU: 1.00, ASIA: 1.00 }

# === micro triggers (추세에서만 사용) ===
micro:
  break_lookback: 10               # 최근 N봉 돌파 확인
  rsi_on: 58.0                     # 롱 최소 RSI (숏은 42에 해당)
  mode: "pierce"                   # "pierce" | "close"
  use_regime_gate: true
  use_mtf_align: false             # 필요 시 true로 전환
  mtf_rsi_min: 55.0
  mtf_mode: "and"
  use_ema_align: false
  ema_col: "ema21"
  min_atr_pct: 0.0
  max_atr_pct: 0.0
  vol_spike_mult: 0.0              # 먼저 0으로 → 신호 충분해지면 1.5~1.6 테스트
  vol_ma_len: 50
  darvas_confirm: false
  cooloff_bars: 0
  # NEW: RSI 극단/교차 파라미터(FOD/SOD 극점 탐지)
  rsi_extrema:
    enable: true
    peak_thr: 70.0                 # 과매수 경계
    trough_thr: 30.0               # 과매도 경계
    window: 3                      # 최근 N바 내 극점 발생 플래그
    require_sod: true              # 2차조건(가속도)로 극점 확인

# === detectors ===
detectors:
  enable: true
  divergence: { enable: true, lookback_swings: 60 }
  fib:
    enable: true
    lookback: 120
    epsilon_pct: 0.15
    include_extra: true            # 0.707/0.786 같은 추가 레벨
    extra_retracements: [0.786]    # features/스코어러에서 안전 처리됨
    extra_extensions: []
    extra_level_eps_pct: 0.06
    atr_floor_mult: 0.25
  darvas: { enable: true, channel_min_bars: 20, breakout_confirm_bars: 2 }

# === filters (하드 게이트) ===
filters:
  trade_in_regimes: ["trend"]      # 안정 모드: 추세 전용

  # 5m/15m MTF 게이트(레거시 보조)
  require_mtf: true
  mtf_apply_in: ["trend"]
  mtf_rsi_mode: "and"
  mtf_rsi_min: 56.0                # 너무 높이면 마름 → 56부터 시작해 튠
  mtf_use_ema_gate: true

  # MACD 히스토그램 부호 일치 + deadband
  require_macd_hist_sign: true
  macd_apply_in: ["trend"]
  macd_deadband_mode: "pct_of_atr"
  macd_deadband_pct: 0.08          # ATR의 8%

  # (A) 거래량 스파이크 하드 게이트 — 초기엔 OFF 권장(신호 말림 방지)
  volume_spike_gate:
    enable: false                  # 먼저 false로 성능 확인 → true, mult 1.5~1.6로 튠
    apply_in: ["trend"]
    mult: 1.6
    ma_len: 50

  # (B) EMA 기울기 방향 일치 게이트 — 추세에서만
  ema_slope_gate:
    enable: true
    apply_in: ["trend"]
    min: 0.0006
    lookback: 5

  # (C) Extreme RSI block — 과열 직후 엔트리 억제(엔진이 rsi_peak/trough_recent 사용)
  extreme_rsi_block:
    enable: true

  # 레인지 모드 파라미터(현재 미사용, 보관)
  range_edge_low: 0.25
  range_edge_high: 0.75
  range_rsi_long_max: 43
  range_rsi_short_min: 57
  range_bbw_min: 0.0009
  range_bbw_max: 0.0050
  range_atr_pct_max: 0.0060

# === soft TP ===
soft_tp:
  enable: true
  r_min: 2.0                       # 최소 이익 이후 페이드 고려
  r_hard: 4.5
  macd_flip: true
  rsi_fade: 50.5

# === scoring ===
scoring_weights: { volatility: 0.25, momentum: 0.25, volume: 0.20, structure: 0.20, fib: 0.10 }

scoring:
  logistic_cap: true
  logistic_mid: 60.0
  logistic_k: 12.0
  detector_bonuses:
    bull_div_rsi: 2.5
    bear_div_rsi: 2.5
    bull_div_macd: 1.5
    bear_div_macd: 1.5
    darvas_up:    2.0
    darvas_dn:    2.0
    near_fib_382: 0.6
    near_fib_500: 0.5
    near_fib_618: 1.0
    near_ext_127: 0.5
    near_ext_161: 0.7
    near_fib_707: 0.5
    near_fib_786: 0.6

# root-level도 읽히므로 동일 보너스 복제(엔진 호환성)
detector_bonuses:
  bull_div_rsi: 2.5
  bear_div_rsi: 2.5
  bull_div_macd: 1.5
  bear_div_macd: 1.5
  darvas_up:    2.0
  darvas_dn:    2.0
  near_fib_382: 0.6
  near_fib_500: 0.5
  near_fib_618: 1.0
  near_ext_127: 0.5
  near_ext_161: 0.7
  near_fib_707: 0.5
  near_fib_786: 0.6
